repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'f4d7745e17a28aad7eed2f4874ca8d1568c11c4c' # v22.1.8
    hooks:
      - id: clang-format
        files: \.(h|hpp|c|cpp)$
  - repo: https://github.com/BlankSpruce/gersemi-pre-commit
    rev: "e98930bdc210d3387007f9252d8c1694ea7e410f" # 0.27.7
    hooks:
      - id: gersemi
  - repo: https://github.com/psf/black
    rev: '87928e6d6761a4a6d22250e1fee5601b3998086e' # 26.5.1
    hooks:
      - id: black
